# CMake generated Testfile for 
# Source directory: /vagrant/scenarios/rsu_grid
# Build directory: /vagrant/scenarios/rsu_grid
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(rsu_grid-omnidirectional "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/scenarios/highway-police/libartery_police.so" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-comnidirectional_test")
set_tests_properties(rsu_grid-omnidirectional PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/rsu_grid")
add_test(rsu_grid-directional "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/scenarios/highway-police/libartery_police.so" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cdirectional_test")
set_tests_properties(rsu_grid-directional PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/rsu_grid")
add_test(rsu_grid-rsu_sensors "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/scenarios/highway-police/libartery_police.so" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-crsu_sensors_test")
set_tests_properties(rsu_grid-rsu_sensors PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/rsu_grid")
