# CMake generated Testfile for 
# Source directory: /vagrant/scenarios/gemv2
# Build directory: /vagrant/scenarios/gemv2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(gemv2-LOS "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cLOS_mediumAntennas" "--sim-time-limit=10s")
set_tests_properties(gemv2-LOS PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/gemv2")
add_test(gemv2-NLOSv "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cNLOSv" "--sim-time-limit=10s")
set_tests_properties(gemv2-NLOSv PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/gemv2")
add_test(gemv2-NLOSbLogDist "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cNLOSb1" "--sim-time-limit=10s")
set_tests_properties(gemv2-NLOSbLogDist PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/gemv2")
add_test(gemv2-NLOSbDifRefl "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cNLOSb1_diffractionReflection" "--sim-time-limit=10s")
set_tests_properties(gemv2-NLOSbDifRefl PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/gemv2")
add_test(gemv2-NLOSbSmallScale "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cNLOSb1_smallScaleVariations" "--sim-time-limit=10s")
set_tests_properties(gemv2-NLOSbSmallScale PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/gemv2")
