# CMake generated Testfile for 
# Source directory: /vagrant/scenarios/storyboard
# Build directory: /vagrant/scenarios/storyboard
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(storyboard-inet "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/scenarios/highway-police/libartery_police.so" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "--sim-time-limit=60s")
set_tests_properties(storyboard-inet PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/storyboard")
add_test(storyboard-veins "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/scenarios/highway-police/libartery_police.so" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cveins" "--sim-time-limit=60s")
set_tests_properties(storyboard-veins PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/storyboard")
add_test(storyboard-repeat "/opt/omnetpp/bin/opp_run_release" "-n" "/vagrant/src/artery:/vagrant/src/traci:/vagrant/extern/veins/examples/veins:/vagrant/extern/veins/src/veins:/vagrant/extern/inet/src:/vagrant/extern/inet/examples:/vagrant/extern/inet/tutorials:/vagrant/extern/inet/showcases" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/scenarios/highway-police/libartery_police.so" "-l" "/vagrant/src/artery/envmod/libartery_envmod.so" "-l" "/vagrant/src/artery/storyboard/libartery_storyboard.so" "-l" "/vagrant/extern/libINET.so" "-l" "/vagrant/extern/libveins.so" "-l" "/vagrant/src/traci/libtraci.so" "-l" "/vagrant/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-crepeat")
set_tests_properties(storyboard-repeat PROPERTIES  WORKING_DIRECTORY "/vagrant/scenarios/storyboard")
